"""Adicionar coluna itens na entidade Pedido

Revision ID: 658af2abd31c
Revises: a2e666d1b611
Create Date: 2025-11-10 23:14:45.903941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '658af2abd31c'
down_revision: Union[str, Sequence[str], None] = 'a2e666d1b611'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
